### ISSUE TITLE
Video problems android

### ISSUE THREAD

**Issue by branchgabriel** [Minds/mobile-native#18]
Cant full screen
Cant track 

Fail fail fail fail fail
Get yo sheet together minds ffs

**Comment by markharding** [comment]
We use github for technical and code related issues only. Please checkout the Help & Support group on Minds.com for more information.

**Comment by branchgabriel** [comment]
Are you saying this is a feature request?

**Comment by Serkan-devel** [comment]
@branchgabriel for context https://github.com/Minds/minds/issues/94
