### ISSUE TITLE
Bottom spacing on iPhone X

### ISSUE THREAD

**Issue by daminufe** [Minds/mobile-native#6]
Hello, I just came across a bug on iOS, that is not urgent but would be nice to get solved. 
I own an iphone X and the bottom screen is tight with the iphone X's "home" button.

*Steps to reproduce:*
1. Opened a comment notification
1. Start typing the answer
1. The following happens:

![](https://user-images.githubusercontent.com/4832774/39268305-bc793fce-48cf-11e8-9c2b-6156b480afcf.jpeg)

![](https://user-images.githubusercontent.com/4832774/39268353-ea954c04-48cf-11e8-9df3-91be609f2c7b.jpeg)

**Comment by Serkan-devel** [comment]
Look for a similar issue on the upstream react-native at https://github.com/facebook/react-native

**Comment by Serkan-devel** [comment]
Could this be the issue https://github.com/facebook/react-native/issues/18141?

**Comment by markharding** [comment]
We have a fix for this internally and will be pushing soon (when published on the app stores)

**Comment by daminufe** [comment]
Awesome @markharding. I'll leave it open until you launch the new version, and then I will test and let you know! Good job 👍

**Comment by Serkan-devel** [comment]
@markharding will you push the fix also to upstream?

**Comment by markharding** [comment]
Yes

**Comment by markharding** [comment]
I believe this fixes the issue https://github.com/Minds/mobile-native/commit/f455a6bd008aad1141cbbdcd051399c8b7ac5191. iOS currently in review with apple and should be available in a couple days.
